// Generated by ts-to-zod
import { z } from "zod";

export const assetTargetSchema = z.object({
  hint: z.string().optional(),
  key: z.string(),
  basePath: z.string(),
  extensions: z.union([z.string(), z.boolean()]),
});

export const iConfigSchema = z.object({
  extenions: z.string().optional(),
  targets: z.array(assetTargetSchema),
});
